### ISSUE TITLE
How to use this in a magento installation??

### ISSUE THREAD

**Issue by mnishihan** [springimport/magento2-swagger-api#1]
You referenced this package as a fix for https://github.com/magento/magento2/issues/7511

But I could not figure out on how to use this in a live magento 2.1.x installation installed from source??

**Comment by springimport** [comment]
@mnishihan [Create Integration](https://www.mageplaza.com/kb/how-to-create-new-api-information-for-integration-magento-2.html) in admin panel. Install `swagger-magento2-client` to your _side_ project. Add access token & host to config.
```php
use SpringImport\Swagger\Magento2\Client\ApiClient;
use SpringImport\Swagger\Magento2\Client\Configuration;
```
```php
$apiConfig = new Configuration();
$apiConfig->setHost('your-host');
$apiConfig->addDefaultHeader('Authorization', 'Bearer your-access-token');
```

If you want to use fixed version of searchCriteria use this dependency in composer.json.
```
"springimport/swagger-magento2-client": "dev-fix-searchcriteria-index"
```

**Comment by mnishihan** [comment]
Actually I'm pretty new in magento development, but has firm experience with other php CMS & frameworks.

In my current requirement, I want to use magento, as an API backend for our custom developed SPA frontend. So, I'm actually not sure, where to put the code you suggested. Do I need to create a separate project with suggested composer dependency and write the code to invoke swagger client?? Or modify some code in magento code base to fix the swagger documentation generation bug as described in https://github.com/magento/magento2/issues/7511 ??

I'm sorry if my questions are too way dumb. But getting a little more guided advice would be very much appreciable.

Thanks in advance.

**Comment by springimport** [comment]
@mnishihan
> So, I'm actually not sure, where to put the code you suggested.
> Do I need to create a separate project
> our custom developed SPA frontend.

I think you already have a backend for your SPA. Add dependency on backend and use.
